# Generated by Django 5.2.1 on 2025-07-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
