# Generated by Django 5.1.7 on 2025-03-21 22:10

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authorprofile_sellerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated date'),
        ),
    ]
