# Generated by Django 5.1.7 on 2025-03-21 22:52

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_authorprofile_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
