# Generated by Django 5.1.7 on 2025-05-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
