# Generated by Django 5.1.7 on 2025-07-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_team_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.team'),
        ),
    ]
