# Generated by Django 5.1.7 on 2025-03-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='last_updated',
            new_name='updated_date',
        ),
    ]
