# Generated by Django 5.2.1 on 2025-07-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=850, null=True, upload_to='categories/'),
        ),
    ]
