# Generated by Django 5.1.7 on 2025-03-22 05:14

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='Date when the article was created'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, help_text='Date when the article was last modified'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='Date when the comment was created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, help_text='Date when the comment was last modified'),
        ),
    ]
