# Generated by Django 5.2.1 on 2025-07-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userprofile_profile_delete_sellerprofile'),
        ('blog', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(help_text='The user who wrote this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='accounts.profile'),
        ),
    ]
