# Generated by Django 5.1.7 on 2025-03-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_body_remove_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
