# Generated by Django 5.2.1 on 2025-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the article should be published automatically', null=True),
        ),
    ]
