# Generated by Django 5.1.7 on 2025-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_articletranslation_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the player', max_length=250)),
                ('image', models.ImageField(blank=True, help_text='Profile image of the player', null=True, upload_to='players/')),
                ('number', models.IntegerField(blank=True, help_text='The jersey number of the player', null=True)),
                ('position', models.CharField(choices=[('DEFENDER', 'مدافع'), ('MIDFIELDER', 'هافبک'), ('FORWARD', 'مهاجم'), ('GOALKEEPER', 'دروازه\u200cبان')], help_text='The position of the player on the field', max_length=20)),
                ('goals', models.IntegerField(blank=True, help_text='The number of goals scored by the player', null=True)),
                ('games', models.IntegerField(blank=True, help_text='The number of games played by the player', null=True)),
            ],
        ),
    ]
