# Generated by Django 5.1.7 on 2025-04-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ipaddress'),
        ('blog', '0008_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hist',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='accounts.ipaddress'),
        ),
    ]
