# Generated by Django 5.2.1 on 2025-07-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_scheduled_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
