# Generated by Django 5.1.7 on 2025-04-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_hist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hist',
            new_name='hits',
        ),
    ]
