# Generated by Django 5.1.7 on 2025-04-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ipaddress'),
        ('blog', '0010_rename_hist_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.CreateModel(
            name='ArticleMiddel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_middle_models', to='blog.article')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_middle_models', to='accounts.ipaddress')),
            ],
            options={
                'verbose_name': 'Article Middle Model',
                'verbose_name_plural': 'Article Middle Models',
            },
        ),
    ]
