# Generated by Django 5.1.7 on 2025-04-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ipaddress'),
        ('blog', '0011_remove_article_hits_articlemiddel'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', through='blog.ArticleMiddel', to='accounts.ipaddress'),
        ),
    ]
