# Generated by Django 5.1.7 on 2025-04-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ipaddress'),
        ('blog', '0012_article_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemiddel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='articlemiddel',
            unique_together={('article', 'ip_address')},
        ),
    ]
