# Generated by Django 5.1.7 on 2025-05-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articlemiddel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.DeleteModel(
            name='ArticleMiddel',
        ),
    ]
