# Generated by Django 5.2.1 on 2025-05-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_ipaddress_middlearticleipaddress_article_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to='blog.ipaddress'),
        ),
        migrations.AlterField(
            model_name='middlearticleipaddress',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_articles', to='blog.article'),
        ),
        migrations.AlterField(
            model_name='middlearticleipaddress',
            name='ipaddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_articles', to='blog.ipaddress'),
        ),
    ]
