# Generated by Django 5.2.1 on 2025-05-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_article_image_article_type_article_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
