# Generated by Django 5.2.1 on 2025-05-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_article_video_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlidShow',
            new_name='Image',
        ),
    ]
