# Generated by Django 5.2.1 on 2025-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_slidshow_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ManyToManyField(related_name='article_images', to='blog.article'),
        ),
    ]
