# Generated by Django 5.2.1 on 2025-06-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_team_teamtranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
