# Generated by Django 5.2.1 on 2025-06-14 09:07

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Profile image of the player', null=True, upload_to='players/')),
                ('number', models.IntegerField(blank=True, help_text='The jersey number of the player', null=True)),
                ('position', models.CharField(choices=[('DEFENDER', 'مدافع'), ('MIDFIELDER', 'هافبک'), ('FORWARD', 'مهاجم'), ('GOALKEEPER', 'دروازه\u200cبان')], help_text='The position of the player on the field', max_length=20)),
                ('goals', models.IntegerField(blank=True, help_text='The number of goals scored by the player', null=True)),
                ('games', models.IntegerField(blank=True, help_text='The number of games played by the player', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlayerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='The name of the player', max_length=250)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translitions', to='blog.player')),
            ],
            options={
                'verbose_name': 'player Translation',
                'db_table': 'blog_player_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModel, models.Model),
        ),
    ]
