# Generated by Django 5.2.1 on 2025-06-22 22:41

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_player_playertranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.player'),
        ),
    ]
