# Generated by Django 5.2.1 on 2025-06-27 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_playertranslation_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='team',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='article', to='blog.team'),
            preserve_default=False,
        ),
    ]
