# Generated by Django 5.2.1 on 2025-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_article_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='The category of this article', null=True, to='blog.category'),
        ),
    ]
